openapi: 3.0.0
info:
  title: To-Do Application API
  version: 1.0.0
paths:
  /crud/todos:
    get:
      summary: Get all to-do items
      responses:
        '200':
          description: A list of to-do items.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Create a new to-do item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTodo'
      responses:
        '201':
          description: The created to-do item.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
  /crud/todos/{id}:
    get:
      summary: Get a specific to-do item
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The requested to-do item.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: To-do item not found.
    put:
      summary: Update a to-do item
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTodo'
      responses:
        '200':
          description: The updated to-do item.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: To-do item not found.
    delete:
      summary: Delete a to-do item
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: To-do item deleted successfully.
        '404':
          description: To-do item not found.
  /chat:
    post:
      summary: Interact with the chatbot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '200':
          description: The chatbot's response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
        due_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    NewTodo:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        due_at:
          type: string
          format: date-time
    UpdateTodo:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
        due_at:
          type: string
          format: date-time
